server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        # 1. AUTH SERVICE
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:https://auth-service-swo5.onrender.com}
          predicates:
            - Path=/auth/**

        # 2. USER SERVICE
        - id: user-service
          uri: ${USER_SERVICE_URL:https://user-service-200f.onrender.com}
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        # 3. PRODUCT SERVICE
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:https://product-service-dy93.onrender.com}
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        # 4. ORDER SERVICE
        - id: order-service
          uri: ${ORDER_SERVICE_URL:https://order-service-26fm.onrender.com}
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

jwt:
  secret: ${JWT_SECRET}
