server:
  port: 8080

spring:
  cloud:
    cloud:
    config:
    uri: ${SPRING_CLOUD_CONFIG_URI:lo_llama_del_orquestador_en_dev}
    username: ${SPRING_CLOUD_CONFIG_USERNAME:admin}
    password: ${SPRING_CLOUD_CONFIG_PASSWORD:admin}
    fail-fast: true
    gateway:
      routes:
        # 1. AUTH SERVICE (PÚBLICO)
        - id: auth-service
          uri: http://auth-service-dev:9000
          predicates:
            - Path=/auth/**

        # 2. USER SERVICE (PROTEGIDO)
        - id: user-service
          uri: http://user-service-dev:8081
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        # 3. PRODUCT SERVICE (PROTEGIDO)
        - id: product-service
          uri: http://product-service-dev:8082
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        # 4. ORDER SERVICE (PROTEGIDO)
        - id: order-service
          uri: http://order-service-dev:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter