server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        # 1. AUTH SERVICE
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:https://tu-auth-service.onrender.com}
          predicates:
            - Path=/auth/**

        # 2. USER SERVICE
        - id: user-service
          uri: ${USER_SERVICE_URL:https://tu-user-service.onrender.com}
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        # 3. PRODUCT SERVICE
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:https://tu-product-service.onrender.com}
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        # 4. ORDER SERVICE
        - id: order-service
          uri: ${ORDER_SERVICE_URL:https://tu-order-service.onrender.com}
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

jwt:
  secret: ${JWT_SECRET}
