server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        # 1. AUTH SERVICE
        - id: auth-service
          uri: http://auth-service:9000
          predicates:
            - Path=/auth/**

        # 2. USER SERVICE
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        # 3. PRODUCT SERVICE
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        # 4. ORDER SERVICE
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000