server:
  port: ${PORT:9000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration/prod
    baseline-on-migrate: true

jwt:
  # Esta variable debe ser la misma que definas para el API Gateway en Render
  secret: ${JWT_SECRET}
  expiration: 3600000