server:
  port: ${PORT:9000}

spring:
  datasource:
    url: jdbc:postgresql://ep-silent-dawn-a4x7xqft-pooler.us-east-1.aws.neon.tech/authdb?sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  flyway:
    repair-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
