server:
  port: ${PORT:9000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  default-schema: auth_schema
  create-schemas: true
  locations: classpath:db/migration/prod
  baseline-on-migrate: true
  ignore-migration-locations: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
