server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    # Estas variables las configuraremos en el panel de Render
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration/prod
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# CONFIGURACIÓN DE COMUNICACIÓN INTERNA
# En Render, usamos el nombre del servicio definido en el render.yaml
user:
  service:
    url: http://user-service:8081
