server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  flyway:
    enabled: true
    default-schema: user_schema
    create-schemas: true
    locations: classpath:db/migration/prod
    baseline-on-migrate: true
    ignore-migration-locations: true

  jpa:
    hibernate:
      ddl-auto: validate # En prod es más seguro validar que actualizar
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
