server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    # Render inyectará estos valores desde el panel de "Environment Variables"
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration/prod
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate # En prod es más seguro validar que actualizar
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
