server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      # Si quieres que Hibernate cree tablas si Flyway falla: usa 'update'
      # Si confías plenamente en tus scripts de Flyway: usa 'validate'
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    enabled: true
    schemas: public
    baseline-on-migrate: true
    check-location: true
    validate-on-migrate: false
